export type Command = {
  name: string;
  syntax: string;
  purpose: string;
};

export type CommandCategory = {
  id: string;
  title: string;
  icon: string;
  blurb: string;
  usage: string;
  commands: Command[];
};

export const categories: CommandCategory[] = [
  {
    id: "moderation",
    title: "Moderation",
    icon: "🛡️",
    blurb: "Human-in-the-loop tools for bans, timeouts, roles, and channel control.",
    usage: "Run from any server channel you can manage. Required arguments must be filled; optional ones refine the action.",
    commands: [
      { name: "/ban", syntax: "/ban <user> [reason] [delete_days]", purpose: "Permanently remove a member and optionally purge their recent messages." },
      { name: "/unban", syntax: "/unban <user> [reason]", purpose: "Lift a ban so the user can rejoin the server." },
      { name: "/kick", syntax: "/kick <user> [reason]", purpose: "Remove a member without placing a ban." },
      { name: "/timeout", syntax: "/timeout <user> <duration> [reason]", purpose: "Temporarily mute a member from chatting and speaking." },
      { name: "/untimeout", syntax: "/untimeout <user> [reason]", purpose: "Clear an active timeout immediately." },
      { name: "/warn", syntax: "/warn <user> <reason>", purpose: "Issue a recorded warning that feeds into later moderation decisions." },
      { name: "/warnings", syntax: "/warnings <user>", purpose: "Inspect a member’s warning history." },
      { name: "/clear", syntax: "/clear <amount> [user]", purpose: "Bulk-delete recent messages, optionally from one member." },
      { name: "/slowmode", syntax: "/slowmode <seconds> [channel]", purpose: "Limit how often members can send messages in a channel." },
      { name: "/lock", syntax: "/lock [channel] [reason]", purpose: "Prevent members from sending messages in a channel." },
      { name: "/unlock", syntax: "/unlock [channel]", purpose: "Restore sending permissions after a lock." },
      { name: "/role", syntax: "/role <user> <role> [action]", purpose: "Add or remove a role from a member." },
      { name: "/nickname", syntax: "/nickname <user> [nickname]", purpose: "Set or reset a member’s server nickname." },
    ],
  },
  {
    id: "automod",
    title: "AutoMod",
    icon: "🤖",
    blurb: "Automated filters that catch spam, links, language, and raid patterns as they happen.",
    usage: "Configure rules once, then AutoMod enforces them continuously. Start with /automod setup.",
    commands: [
      { name: "/automod setup", syntax: "/automod setup [channel]", purpose: "Initialize AutoMod with recommended defaults for this server." },
      { name: "/automod spam", syntax: "/automod spam <enabled> [threshold]", purpose: "Detect and act on rapid duplicate or flood messages." },
      { name: "/automod links", syntax: "/automod links <mode> [allowlist]", purpose: "Control which links are allowed, blocked, or invited-only." },
      { name: "/automod words", syntax: "/automod words <action> [word]", purpose: "Maintain a blocked-word list and the response to matches." },
      { name: "/automod mentions", syntax: "/automod mentions <limit> [action]", purpose: "Stop mass-mention abuse before it pings the whole server." },
      { name: "/automod caps", syntax: "/automod caps <enabled> [percent]", purpose: "Flag messages that are overwhelmingly uppercase." },
      { name: "/automod raids", syntax: "/automod raids <enabled> [join_rate]", purpose: "Trigger raid-mode when join velocity spikes." },
      { name: "/automod actions", syntax: "/automod actions <rule> <action>", purpose: "Map each AutoMod rule to warn, timeout, kick, or delete." },
    ],
  },
  {
    id: "protection",
    title: "Server Protection",
    icon: "🛡️",
    blurb: "Hardening layer for raids, bot waves, and nuke attempts — beyond day-to-day moderation.",
    usage: "Keep a log channel and a trusted whitelist. Use lockdown when an incident is active.",
    commands: [
      { name: "/protection setup", syntax: "/protection setup [log_channel]", purpose: "Enable the protection suite and choose where alerts are posted." },
      { name: "/protection status", syntax: "/protection status", purpose: "Show which shields are armed and current threat posture." },
      { name: "/protection lockdown", syntax: "/protection lockdown [reason]", purpose: "Instantly restrict joins and high-risk permissions." },
      { name: "/protection unlock", syntax: "/protection unlock", purpose: "Restore normal access after an incident." },
      { name: "/protection anti-raid", syntax: "/protection anti-raid <enabled> [sensitivity]", purpose: "Tune automatic raid detection and join gating." },
      { name: "/protection anti-bot", syntax: "/protection anti-bot <enabled> [age_days]", purpose: "Block or quarantine newly created bot and alt accounts." },
      { name: "/protection anti-nuke", syntax: "/protection anti-nuke <enabled>", purpose: "Watch for mass bans, channel wipes, and role deletions." },
      { name: "/protection whitelist", syntax: "/protection whitelist <user> [action]", purpose: "Exempt trusted staff from protection triggers." },
      { name: "/protection logs", syntax: "/protection logs [channel]", purpose: "Set or inspect the security incident log channel." },
      { name: "/protection scan", syntax: "/protection scan [depth]", purpose: "Audit the server for risky permissions and suspicious bots." },
    ],
  },
  {
    id: "reminders",
    title: "Advanced Reminders",
    icon: "⏰",
    blurb: "Personal and server reminders with repeats, pauses, and per-user timezones.",
    usage: "Times accept natural language or ISO-style durations. Set a timezone once for accurate delivery.",
    commands: [
      { name: "/reminder create", syntax: "/reminder create <when> <message> [channel]", purpose: "Schedule a new reminder for yourself or a channel." },
      { name: "/reminder list", syntax: "/reminder list [scope]", purpose: "Browse upcoming reminders you can manage." },
      { name: "/reminder edit", syntax: "/reminder edit <id> [when] [message]", purpose: "Change the time or copy of an existing reminder." },
      { name: "/reminder delete", syntax: "/reminder delete <id>", purpose: "Cancel a reminder permanently." },
      { name: "/reminder pause", syntax: "/reminder pause <id>", purpose: "Hold a repeating reminder without deleting it." },
      { name: "/reminder resume", syntax: "/reminder resume <id>", purpose: "Restart a paused reminder on its original cadence." },
      { name: "/reminder repeat", syntax: "/reminder repeat <id> <interval>", purpose: "Convert a one-shot reminder into a recurring one." },
      { name: "/reminder timezone", syntax: "/reminder timezone <zone>", purpose: "Set the timezone used to interpret your reminder times." },
    ],
  },
  {
    id: "leveling",
    title: "Leveling",
    icon: "📈",
    blurb: "XP, ranks, and role rewards for members who participate in the server.",
    usage: "Enable leveling, then attach roles and multipliers. Blacklist channels that should not grant XP.",
    commands: [
      { name: "/level", syntax: "/level [user]", purpose: "Show a member’s current level and XP progress." },
      { name: "/rank", syntax: "/rank [user]", purpose: "Display a rank card with position on the server ladder." },
      { name: "/leaderboard", syntax: "/leaderboard [page]", purpose: "List the highest-XP members in this server." },
      { name: "/levels", syntax: "/levels [user]", purpose: "Open a compact overview of level thresholds and rewards." },
      { name: "/leveling setup", syntax: "/leveling setup [enabled]", purpose: "Turn the XP system on and choose baseline rates." },
      { name: "/leveling rewards", syntax: "/leveling rewards <level> <role>", purpose: "Grant a role automatically when a level is reached." },
      { name: "/leveling multipliers", syntax: "/leveling multipliers <target> <rate>", purpose: "Boost or reduce XP in specific roles or channels." },
      { name: "/leveling roles", syntax: "/leveling roles [action]", purpose: "Review and clean up level-reward role mappings." },
      { name: "/leveling blacklist", syntax: "/leveling blacklist <channel> [action]", purpose: "Exclude channels from granting XP." },
    ],
  },
  {
    id: "achievements",
    title: "Achievements",
    icon: "🏆",
    blurb: "Custom milestones that recognize moderation help, activity, and server lore.",
    usage: "Members view progress; admins create and edit achievements that hook into events.",
    commands: [
      { name: "/achievements", syntax: "/achievements [user]", purpose: "Show unlocked achievements for a member." },
      { name: "/achievement list", syntax: "/achievement list [filter]", purpose: "Browse every achievement available on this server." },
      { name: "/achievement progress", syntax: "/achievement progress [user] [id]", purpose: "See how close a member is to unlocking an achievement." },
      { name: "/achievement leaderboard", syntax: "/achievement leaderboard [page]", purpose: "Rank members by achievements earned." },
      { name: "/achievement create", syntax: "/achievement create <name> <condition> [reward]", purpose: "Define a new server achievement (admin)." },
      { name: "/achievement edit", syntax: "/achievement edit <id> [name] [condition] [reward]", purpose: "Update an existing achievement’s rules or reward." },
      { name: "/achievement delete", syntax: "/achievement delete <id>", purpose: "Remove an achievement and its progress tracking." },
    ],
  },
  {
    id: "giveaways",
    title: "Giveaways",
    icon: "🎁",
    blurb: "Fair, pausable prize drops with entry tracking and rerolls.",
    usage: "Create a draft, start it in a channel, then end or reroll when the timer completes.",
    commands: [
      { name: "/giveaway create", syntax: "/giveaway create <prize> <duration> [winners]", purpose: "Draft a giveaway with prize, length, and winner count." },
      { name: "/giveaway start", syntax: "/giveaway start <id> [channel]", purpose: "Publish a drafted giveaway and open entries." },
      { name: "/giveaway end", syntax: "/giveaway end <id>", purpose: "Close entries early and draw winners." },
      { name: "/giveaway reroll", syntax: "/giveaway reroll <id> [count]", purpose: "Pick new winners if someone is ineligible." },
      { name: "/giveaway edit", syntax: "/giveaway edit <id> [prize] [duration] [winners]", purpose: "Adjust prize copy or timing before it ends." },
      { name: "/giveaway pause", syntax: "/giveaway pause <id>", purpose: "Freeze the countdown and stop new entries." },
      { name: "/giveaway resume", syntax: "/giveaway resume <id>", purpose: "Continue a paused giveaway." },
      { name: "/giveaway entries", syntax: "/giveaway entries <id>", purpose: "Show how many members have entered." },
      { name: "/giveaway participants", syntax: "/giveaway participants <id> [page]", purpose: "List members currently entered." },
      { name: "/giveaway list", syntax: "/giveaway list [status]", purpose: "See active, paused, and ended giveaways." },
    ],
  },
  {
    id: "events",
    title: "Events",
    icon: "📅",
    blurb: "Schedule server events, collect RSVPs, and ping participants when it is time.",
    usage: "Create an event, share it, then start/end it to match the live gathering.",
    commands: [
      { name: "/event create", syntax: "/event create <name> <when> [description]", purpose: "Announce a new server event with a start time." },
      { name: "/event edit", syntax: "/event edit <id> [name] [when] [description]", purpose: "Update event details before it begins." },
      { name: "/event cancel", syntax: "/event cancel <id> [reason]", purpose: "Call off an event and notify participants." },
      { name: "/event start", syntax: "/event start <id>", purpose: "Mark the event as live and open participation." },
      { name: "/event end", syntax: "/event end <id>", purpose: "Close the event and archive attendance." },
      { name: "/event list", syntax: "/event list [status]", purpose: "Browse upcoming and past events." },
      { name: "/event participants", syntax: "/event participants <id>", purpose: "See who RSVP’d or joined." },
      { name: "/event remind", syntax: "/event remind <id> [offset]", purpose: "Send a reminder to participants before start." },
    ],
  },
  {
    id: "invites",
    title: "Invite Tracker",
    icon: "🔗",
    blurb: "Attribute joins to invite links and reward members who grow the community.",
    usage: "Use user and leaderboard views for staff reports; rewards for growth campaigns.",
    commands: [
      { name: "/invites", syntax: "/invites [user]", purpose: "Show invite counts and recent joins for a member." },
      { name: "/invites user", syntax: "/invites user <user>", purpose: "Deep-dive a member’s invite performance." },
      { name: "/invites leaderboard", syntax: "/invites leaderboard [page]", purpose: "Rank members by successful invites." },
      { name: "/invites list", syntax: "/invites list [user]", purpose: "List active invite codes and their usage." },
      { name: "/invite info", syntax: "/invite info <code>", purpose: "Inspect a specific invite code, creator, and uses." },
      { name: "/invite leaderboard", syntax: "/invite leaderboard [page]", purpose: "Alternate view of top inviters across the server." },
      { name: "/invite rewards", syntax: "/invite rewards <count> <role>", purpose: "Grant a role when a member reaches an invite milestone." },
    ],
  },
  {
    id: "activity",
    title: "Chat Activity",
    icon: "🔥",
    blurb: "Measure conversation health, surface heatmaps, and schedule activity prompts.",
    usage: "Review stats first, then turn on prompts if quiet hours need a nudge.",
    commands: [
      { name: "/activity", syntax: "/activity [channel]", purpose: "Snapshot recent chat energy for a channel or the server." },
      { name: "/activity stats", syntax: "/activity stats [range]", purpose: "Break down messages, actives, and peak hours." },
      { name: "/activity leaderboard", syntax: "/activity leaderboard [range]", purpose: "Rank the most active conversational members." },
      { name: "/activity heatmap", syntax: "/activity heatmap [channel]", purpose: "Visualize when the community is actually talking." },
      { name: "/activity prompts", syntax: "/activity prompts [enabled]", purpose: "Toggle icebreaker prompts during quiet periods." },
      { name: "/activity setup", syntax: "/activity setup [channel]", purpose: "Choose where activity reports and prompts appear." },
      { name: "/activity schedule", syntax: "/activity schedule <time> [prompt]", purpose: "Plan recurring conversation starters." },
    ],
  },
  {
    id: "relationships",
    title: "Member Relationship Graph",
    icon: "🕸️",
    blurb: "Map who talks with whom so community managers can spot clusters and isolates.",
    usage: "Graphs are computed from recent interactions. Use user view for 1:1 neighborhoods.",
    commands: [
      { name: "/relationships", syntax: "/relationships", purpose: "Open the server’s high-level relationship overview." },
      { name: "/relationships user", syntax: "/relationships user <user>", purpose: "See who a member interacts with most." },
      { name: "/relationships graph", syntax: "/relationships graph [depth]", purpose: "Render a network graph of recent conversations." },
      { name: "/relationships top", syntax: "/relationships top [limit]", purpose: "List the strongest member-to-member connections." },
      { name: "/relationships stats", syntax: "/relationships stats", purpose: "Summarize clustering, reciprocity, and isolated members." },
    ],
  },
  {
    id: "member",
    title: "Member",
    icon: "👤",
    blurb: "Look up profiles, avatars, banners, and server-specific identity at a glance.",
    usage: "Works on yourself if you omit a user. Server profile is guild-specific.",
    commands: [
      { name: "/user", syntax: "/user [user]", purpose: "Show account age, IDs, and public user details." },
      { name: "/profile", syntax: "/profile [user]", purpose: "Open the Alya profile card for a member." },
      { name: "/avatar", syntax: "/avatar [user]", purpose: "Fetch a high-resolution avatar." },
      { name: "/banner", syntax: "/banner [user]", purpose: "Fetch a user’s profile banner if they have one." },
      { name: "/serverprofile", syntax: "/serverprofile [user]", purpose: "Show nickname, roles, and join date in this server." },
      { name: "/memberinfo", syntax: "/memberinfo [user]", purpose: "Combined user + server snapshot for staff lookups." },
    ],
  },
  {
    id: "analytics",
    title: "Analytics",
    icon: "📊",
    blurb: "Server-level trends for members, messages, voice, growth, and retention.",
    usage: "Ranges default to 7 days. Pair with logging for event-level investigation.",
    commands: [
      { name: "/analytics", syntax: "/analytics [range]", purpose: "Executive overview of how the server is trending." },
      { name: "/analytics members", syntax: "/analytics members [range]", purpose: "Joins, leaves, and net member change." },
      { name: "/analytics messages", syntax: "/analytics messages [range]", purpose: "Message volume by channel and time." },
      { name: "/analytics voice", syntax: "/analytics voice [range]", purpose: "Voice-minute totals and peak occupancy." },
      { name: "/analytics growth", syntax: "/analytics growth [range]", purpose: "Invite-driven growth versus organic joins." },
      { name: "/analytics activity", syntax: "/analytics activity [range]", purpose: "Unique actives and engagement ratio." },
      { name: "/analytics retention", syntax: "/analytics retention [cohort]", purpose: "How many new members still participate after joining." },
    ],
  },
  {
    id: "logging",
    title: "Logging",
    icon: "📜",
    blurb: "Route moderation and server events into dedicated log channels you can search later.",
    usage: "Pick channels per event family so staff are not flooded in one stream.",
    commands: [
      { name: "/logs", syntax: "/logs [type]", purpose: "Preview the current logging configuration." },
      { name: "/logs setup", syntax: "/logs setup [channel]", purpose: "Enable logging with a default destination channel." },
      { name: "/logs channels", syntax: "/logs channels <event> <channel>", purpose: "Send a specific event type to its own channel." },
      { name: "/logs events", syntax: "/logs events <event> <enabled>", purpose: "Toggle which events are captured." },
      { name: "/logs search", syntax: "/logs search <query> [user]", purpose: "Find recent log entries matching a user or keyword." },
    ],
  },
  {
    id: "config",
    title: "Server Configuration",
    icon: "⚙️",
    blurb: "One place to wire moderation, AutoMod, leveling, welcome, logs, roles, and alerts.",
    usage: "Run /setup for a guided pass, then use scoped /config commands for fine-tuning.",
    commands: [
      { name: "/setup", syntax: "/setup", purpose: "Walk through first-time Alya configuration." },
      { name: "/config", syntax: "/config", purpose: "Open the master configuration summary." },
      { name: "/config moderation", syntax: "/config moderation [key] [value]", purpose: "Set moderation defaults such as mute role and log style." },
      { name: "/config automod", syntax: "/config automod [key] [value]", purpose: "Adjust AutoMod defaults from the config panel." },
      { name: "/config leveling", syntax: "/config leveling [key] [value]", purpose: "Change XP rates and announcement channels." },
      { name: "/config welcome", syntax: "/config welcome [key] [value]", purpose: "Point welcome flows at the right channel and template." },
      { name: "/config logs", syntax: "/config logs [key] [value]", purpose: "Quick-edit logging destinations." },
      { name: "/config roles", syntax: "/config roles [key] [value]", purpose: "Map staff, mute, and reward roles used by Alya." },
      { name: "/config notifications", syntax: "/config notifications [key] [value]", purpose: "Control which staff pings fire on incidents." },
    ],
  },
  {
    id: "welcome",
    title: "Welcome / Goodbye",
    icon: "👋",
    blurb: "First and last impressions — custom join and leave messages you can preview safely.",
    usage: "Test in a private channel before pointing the live flow at #welcome.",
    commands: [
      { name: "/welcome setup", syntax: "/welcome setup <channel> [message]", purpose: "Configure the join greeting and destination." },
      { name: "/welcome test", syntax: "/welcome test [user]", purpose: "Send a sample welcome without a real join." },
      { name: "/welcome preview", syntax: "/welcome preview", purpose: "Render the current welcome template as it will appear." },
      { name: "/goodbye setup", syntax: "/goodbye setup <channel> [message]", purpose: "Configure the leave message and destination." },
      { name: "/goodbye test", syntax: "/goodbye test [user]", purpose: "Send a sample goodbye message." },
    ],
  },
  {
    id: "intelligence",
    title: "Server Intelligence",
    icon: "🧠",
    blurb: "Alya’s unique diagnostic layer — health scores, reports, and actionable recommendations.",
    usage: "Run /diagnose during incidents and /recommendations weekly for a maintenance pass.",
    commands: [
      { name: "/insights", syntax: "/insights [focus]", purpose: "Surface the most important trends Alya sees right now." },
      { name: "/diagnose", syntax: "/diagnose [area]", purpose: "Investigate a problem area such as raids, silence, or permission drift." },
      { name: "/serverhealth", syntax: "/serverhealth", purpose: "Score security, engagement, and configuration completeness." },
      { name: "/serverreport", syntax: "/serverreport [range]", purpose: "Generate a staff-ready written report of server performance." },
      { name: "/recommendations", syntax: "/recommendations [priority]", purpose: "Get ranked next actions to improve the server." },
    ],
  },
  {
    id: "global",
    title: "Global",
    icon: "🌎",
    blurb: "Cross-server standing for members who use Alya in more than one community.",
    usage: "Global stats are opt-in per server. Ranks never expose private guild data.",
    commands: [
      { name: "/globalrank", syntax: "/globalrank [user]", purpose: "Show a member’s Alya rank across participating servers." },
      { name: "/globalstats", syntax: "/globalstats [user]", purpose: "Aggregate XP, achievements, and activity across guilds." },
      { name: "/globalachievements", syntax: "/globalachievements [user]", purpose: "List achievements earned in any Alya community." },
      { name: "/globalservers", syntax: "/globalservers", purpose: "See how many servers you share Alya with (public count)." },
    ],
  },
  {
    id: "bot",
    title: "Bot",
    icon: "🔧",
    blurb: "Status, help, and links — the utilities you reach for when Alya itself needs a check.",
    usage: "Use /help for in-Discord guidance and /support if you need the human team.",
    commands: [
      { name: "/help", syntax: "/help [command]", purpose: "Interactive help for a command or category." },
      { name: "/about", syntax: "/about", purpose: "Learn what Alya is and the version running here." },
      { name: "/ping", syntax: "/ping", purpose: "Measure round-trip latency to Discord." },
      { name: "/status", syntax: "/status", purpose: "Show shard health, uptime, and incident notices." },
      { name: "/support", syntax: "/support", purpose: "Get the support server invite and ticket guidance." },
      { name: "/invite", syntax: "/invite", purpose: "Generate a link to add Alya to another server." },
    ],
  },
];

export const commandCount = categories.reduce((n, c) => n + c.commands.length, 0);
